categories = [
    {"id": 0, "name": "All categories"},
    {"id": 1, "name": "General Knowledge"},
    {"id": 2, "name": "Entertainment: Books"},
    {"id": 3, "name": "Entertainment: Film"},
    {"id": 4, "name": "Entertainment: Music"},
    {"id": 5, "name": "Entertainment: Musicals & Theatres"},
    {"id": 6, "name": "Entertainment: Television"},
    {"id": 7, "name": "Entertainment: Video Games"},
    {"id": 8, "name": "Entertainment: Board Games"},
    {"id": 9, "name": "Science & Nature"},
    {"id": 10, "name": "Science: Computers"},
    {"id": 11, "name": "Science: Mathematics"},
    {"id": 12, "name": "Mythology"},
    {"id": 13, "name": "Sports"},
    {"id": 14, "name": "Geography"},
    {"id": 15, "name": "History"},
    {"id": 16, "name": "Politics"},
    {"id": 17, "name": "Art"},
    {"id": 18, "name": "Celebrities"},
    {"id": 19, "name": "Animals"},
    {"id": 20, "name": "Vehicles"},
    {"id": 21, "name": "Entertainment: Comics"},
    {"id": 22, "name": "Science: Gadgets"},
    {"id": 23, "name": "Entertainment: Japanese Anime & Manga"},
    {"id": 24, "name": "Entertainment: Cartoon & Animations"}
]

game_dialogs = {
    "welcome": "Welcome to the Trivia Game! Would you like to turn on the voice command for this game?",
    "welcome": "Selamat datang di game trivia paling menyenangkan di dunia! Katakan 'disabilitas' untuk mengaktifkan mode disabilitas. Jika tidak ingin, tekan tombol di paling bawah.",
    "language": "What language do you wish to use?",
    "amount": "How many number of quizzes you wish to generate? Please select between 1 to 50.",
    "jumlah": "Berapa jumlah soal yang anda inginkan? Pilih dari 1 sampai 50.",
    "difficulty": "Please select a difficulty between easy, medium, and hard.",
    "kesulitan": "Mohon pilih tingkat kesulitan dari mudah, sedang dan sulit.",
    "category": "Please select a category between 1 to 24.",
    "kategori": "Mohon untuk memilih kategori dari 1 sampai 24.",
    "type": "Please select a type between multiple choices and boolean.",
    "jenis": "Mohon untuk memilih tipe trivia, pilih antara pilihan ganda dan benar atau salah.",
    "disab_mode": "disability",
    "disabilitas": "Mode disabilitas. Pilih antara jumlah, kesulitan, kategori, jenis, dan main",
    # "disab_mode": "Disability mode activated. To start the game, please set between amount, difficulty, category, and type, according to your liking. If you wish to just start the game, please say generate.",
    "exit": "Okay, thank you for playing this game. Have a good day!"
}
